{"name": "testlogin_1", "status": "failed", "statusDetails": {"message": "AssertionError: assert '登录失败' == '登录成功'\n  - 登录成功\n  + 登录失败", "trace": "def testlogin_1():\n        # - case1: 测试数据：admin,123456，期望结果：登录成功\n        # 测试数据\n        username = 'admin'\n        passwd = '123456'\n        excepted = '登录成功'\n        # 实际结果\n        actual = login(username,passwd)\n        # 断言\n>       assert actual == excepted\nE       AssertionError: assert '登录失败' == '登录成功'\nE         - 登录成功\nE         + 登录失败\n\ntest_login_d2.py:21: AssertionError"}, "start": 1685672092854, "stop": 1685672092855, "uuid": "83d74928-7fd5-4765-9f81-8a189af4ab0e", "historyId": "5344c6df56cb503deb9b2960aad48cfb", "testCaseId": "5344c6df56cb503deb9b2960aad48cfb", "fullName": "test_login_d2#testlogin_1", "labels": [{"name": "suite", "value": "test_login_d2"}, {"name": "host", "value": "010A2007290050"}, {"name": "thread", "value": "30060-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_login_d2"}]}